services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        # Picked up from the .env file
        USERNAME: ${USER}
        USER_UID: ${UID}
        USER_GID: ${GID}

    volumes:
      # GIT_ROOT is picked up from .env file
      - ${GIT_ROOT}:/workspaces/misc:cached

    # Set working dir as the current dir
    working_dir: /workspaces/misc/algorithms/fast_inverse_square_root/cpp                                              

    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
