services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        USERNAME: ${USER:-$(whoami)}
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}

    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ${GIT_ROOT}:/workspaces/misc:cached

    working_dir: /workspaces/misc/algorithms/fast_inverse_square_root/cpp                                              

    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
